server:
#  port : 8082
  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부 default: false
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부 default: never
    path: '/error' # 오류 응답을 처리할 Handler의 경로
    whitelabel.enabled: true # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부
  email: extworld@gmail.com
  ip: 127.0.0.1
  path: /localhost


logging:
  #output to a temp_folder/file
  #file: /logs/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework: DEBUG
    com:
      tobe:
        fishing:
          pagination=debug: debug
#fishkingV2\src\main\resources\static\
#File location
file :
#    location : C:\Users\kai\Desktop\fishkingV2\src\main\resources\static\files
#    downloadUrl : localhost:8082/files
  location :  /usr/local/tomcat/webapps/upload/data/file
  downloadUrl : http://112.220.72.178:6081/resource
encrypKey :
  key : fishking12345abcde

spring:

  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    fremaker:
      cache: false
  # server.servlet.context-path=/portal
  servlet:
    multipart:
      max-file-size : 2MB
      max-request-size: 10MB


  datasource:
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver   #<= ms-sql
    # driver-class-name: com.mysql.cj.jdbc.Driver                      #<= mysql
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # sendStringParametersAsUnicode=false =>실행되는 느린 쿼리 수정
    # url: jdbc:sqlserver://192.168.0.58:1700;databaseName=fishking;sendStringParametersAsUnicode=false #<=real
    #url: jdbc:sqlserver://localhost:1433;databaseName=fishking;sendStringParametersAsUnicode=false
    #url: jdbc:log4jdbc:mysql://192.168.0.58:7002/fishking?serverTimezone=UTC&characterEncoding=UTF-8 #=> mysql
    #url: jdbc:log4jdbc:sqlserver://localhost:1433;databaseName=fishking;sendStringParametersAsUnicode=false
    #    url: jdbc:log4jdbc:mysql://localhost:7306/fishking?serverTimezone=UTC&characterEncoding=UTF-8 #=> mysql
#    url: jdbc:log4jdbc:mysql://192.168.0.58:7002/fishking?serverTimezone=UTC&characterEncoding=UTF-8
    url : jdbc:log4jdbc:mysql://112.220.72.178:7002/fishking?serverTimezone=UTC&characterEncoding=UTF-8

    username: fishking      #sa        # username: fishluck
    password: fishking12#$  #P@ssw0rd  # password: fishluck123!
    platform: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # ↓ PostRepository에서 findAllByBoard()호출시 sql문법이 틀렸다는 오류가떠서 db방언을 변경함.
    #(오류정보 : You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near)
    #database-platform: org.hibernate.dialect.MariaDB103Dialect
    #database-platform: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      use_sql_comments: true
      ddl-auto: update
    naming:
      #        strategy: org.hibernate.cfg.EJB3NamingStrategy
      #        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      #        strategy: org.hibernate.cfg.DefaultNamingStrategy
      #        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy


