spring:
  profiles: local

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://116.125.120.86:3306/fishking?serverTimezone=UTC&characterEncoding=UTF-8
    username: fishking      #sa        # username: fishluck
    password: fishking12#$  #P@ssw0rd  # password: fishluck123!
    platform: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      use_sql_comments: true
      ddl-auto: update
    naming:
      strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

  devtools:
    livereload:
      enabled: true

server:
  port: 8083

file :
  location : C:\Users\kai\Desktop\fishkingV2\src\main\resources\static\files
  downloadUrl : localhost:8083/files
#  location: /mnt/nfs/files/
#  downloadUrl: fishkingapp.com/resource
#  location : /usr/local/tomcat/webapps/upload/data/file/
#  downloadUrl : localhost:8083/resource
