spring:
  profiles:
    active: prod
  devtools:
    livereload:
      enabled: true
    fremaker:
      cache: false
  # server.servlet.context-path=/portal
  servlet:
    multipart:
      max-file-size : 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      view-names: jsp/*
  thymeleaf:
    view-names: thymeleaf/*

server:
  port : 8082
  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부 default: false
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부 default: never
    path: '/error' # 오류 응답을 처리할 Handler의 경로
    whitelabel.enabled: true # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부
  email: extworld@gmail.com
  ip: 127.0.0.1
  path: /localhost

#file :
#    location : C:\Users\kai\Desktop\fishkingV2\src\main\resources\static\files
#    downloadUrl : localhost:8082/files
#  location :  /usr/local/tomcat/webapps/upload/data/file/
#  downloadUrl : http://112.220.72.178:6081/resource
encrypKey :
  key : fishking12345abcde