spring:
  profiles: prod

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://116.125.120.86:3306/fishking?serverTimezone=UTC&characterEncoding=UTF-8
    username: fishking      #sa        # username: fishluck
    password: fishking12#$  #P@ssw0rd  # password: fishluck123!
    platform: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      format_sql: true
      use_sql_comments: true
      ddl-auto: update
    naming:
      strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

  devtools:
    livereload:
      enabled: false

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      view-names: jsp/*
    thymeleaf:
      view-names: thymeleaf/*

file :
  location : /mnt/nfs/files/
  downloadUrl : https://www.fishkingapp.com/resource


logging:
  #output to a temp_folder/file
  file:
    path: /opt/tomcat/logs
#    name: 'fishking.log'
#    max-history: 365
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
#  level:
#    org:
#      hibernate:
#        SQL: info
#        type:
#          descriptor:
#            sql:
#              BasicBinder: error
#      springframework: info
#    com:
#      tobe:
#        fishing:
#          pagination=debug: info