# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'native_fishking' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'native_fishkingTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#   use_flipper!({ 'Flipper-Folly' => '2.3.0' })
#   post_install do |installer|
#     fix_deployment_target(installer)
#   end

  # react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

end

target 'native_fishking-tvOS' do
  # Pods for native_fishking-tvOS

  target 'native_fishking-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# def fix_deployment_target(installer)
#   return if !installer
#   project = installer.pods_project
#   project_deployment_target = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
#
#   puts "Make sure all pods deployment target is #{project_deployment_target.green}"
#   project.targets.each do |target|
#     puts "  #{target.name}".blue
#     target.build_configurations.each do |config|
#       old_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
#       new_target = project_deployment_target
#       next if old_target == new_target
#       puts "    #{config.name}: #{old_target.yellow} -> #{new_target.green}"
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = new_target
#     end
#   end
# end
